spring:
  application:
    name: api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

jwt:
  base64-encode-secret-key: k4v7zK8p2q5r9s3t6u1w8x4y7z2a5b8c9d1e3f6g7hg=

server:
  servlet:
    context-path: /api

file:
  resource-dir: D:/resources/
  access-domain: http://localhost:8080
  access-prefix: /files/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.apache.shiro: DEBUG
    com.web.api.mapper: DEBUG
    com.github.pagehelper: DEBUG
---
# 激活的环境配置
spring:
  profiles:
    active: dev